#!/bin/sh
#
# %% Executable hook %%

. $ZDOTDIR/lib/libhost.sh

read_localhost_nickname

# Note xwrits-warn is in seconds but xwrits-lock is in minutes
case "$localhost_nickname" in
    atlantic|indian|pacific|southern)
        cat <<EOF
# Lunchbreak by 12:30pm.  Start nagging at 12pm (note that xwrits
# canceltime defaults to 10 minutes) ...
00    12  *   *   *     run-with-local-X-display quietrun timeout -z '12:30pm' xwrits typetime=0 breaktime=600 +multiply=10
#
# ... with a hard stop at 12:30pm.
30    12  *   *   *     run-with-local-X-display quietrun timeout -z '1:00pm' xwrits typetime=0 breaktime=600 +lock

# ---------------------------
# The old way of doing it - shut the computer down if I misbehave!
#
00    12  *   *  1-5    run-with-local-X-display quietrun routine '12:31pm' '1pm'

# ============================================================================
# Get to bed by 11:30pm.  Start nagging at 11pm (note that xwrits
# canceltime defaults to 10 minutes) ...
00    23  *   *   *     run-with-local-X-display quietrun timeout -v -l $HOME/.timeout.soft-bedtime.$$ -z '6am tomorrow' xwrits typetime=0 breaktime=600 +multiply=10
#
# ... with a hard stop at 11:30pm.
30    23  *   *   *     run-with-local-X-display quietrun timeout -v -l $HOME/.timeout.hard-bedtime.$$ -z '6am tomorrow' xwrits typetime=0 breaktime=600 +lock
#
# The -z option to timeout is necessary to keep quietrun from
# complaining at 6am.

# ---------------------------
# The old way of doing it - shut the computer down if I misbehave!
#
*     23  *   *   *     run-with-local-X-display quietrun routine '11:31pm' '5am tomorrow'
# Should only need this second one if I naughtily killed routine
# process during warning phase.
*/1  0-5  *   *   *     run-with-local-X-display quietrun routine 12am 5am 
EOF
        ;;
esac

case "$localhost_nickname" in
    southern)
        cat <<EOF

# Don't fuck around on facebook etc. for too long during workdays -
# 20 minutes every 3 hours sounds about right.  +quota allows the 20
# minutes to be spread over the 3 hours.
30    09  *   *  1-5    run-with-local-X-display quietrun timeout -z 6pm xwrits typetime=20 breaktime=180 +multiply=600 +quota +lock
EOF
        ;;
esac
