#!/bin/sh
#
# %% Executable hook %%

. $ZDOTDIR/lib/libhost.sh

read_localhost_nickname

case "$localhost_nickname" in
    pacific)
        cat <<EOF
0      7  *   *   *     quietrun run-with-local-X-display -q switch-feed-emacs -l < ~/lib/xmacro/org-agenda-daily-review
EOF
esac
