#!/bin/sh

grep-notes-shortcuts

~/.cfg-post.d/cron
mkdir -p ~/.log/atimeout

for svc in sync commit; do
    unit=auto-$svc-org.service
    systemctl --user enable $unit
    systemctl --user start $unit
done
